name: Release Prod

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ANOTHER_TOKEN }}

      - name: Push main to prod branch
        #env:
        #  GITHUB_TOKEN: ${{ secrets.BETA_TOKEN }}
        run: |
          git config --global user.name "testing"
          git config --global user.email "testing@free.land"
          git checkout prod
          git pull origin main --ff-only
          git push origin prod
